In [1]:
from pyforest import *

In [2]:
dummies = pd.read_csv(r'/Users/dillorr/defaultRate/dillon/defaultRate/data/modeling/dummies.csv', encoding = "ISO-8859-1")
numeric = pd.read_csv(r'/Users/dillorr/defaultRate/dillon/defaultRate/data/modeling/numeric.csv', encoding = "ISO-8859-1")

In [8]:
combined = numeric.join(dummies.set_index('opeid'), on='opeid')
combined.head()

,opeid,agemedian,cdr2014_log,cdr2015_log,cdr2016_log,cohort2014_log,cohort2015_log,cohort2016_log,density_log,educationcollegeorabove,...,nondegree1year,nondegree2years,nondegree3years,private,proprietary,public,hbcuCollege,hispanicCollege,nativeAmericanCollege,notReportedCollege
0,1003,0.300195,0.571828,0.559079,0.617687,0.608946,0.615880,0.582015,0.558779,0.315733,...,0,0,0,1,0,0,0,0,0,1
1,1004,0.161793,0.476093,0.501078,0.502243,0.557466,0.562743,0.525574,0.458710,0.259698,...,0,0,0,0,0,1,0,0,0,1
2,1005,0.300195,0.653403,0.670747,0.725912,0.650509,0.650174,0.611714,0.558779,0.315733,...,0,0,0,0,0,1,1,0,0,0
3,1007,0.385965,0.723561,0.684976,0.717981,0.543909,0.537148,0.479876,0.409677,0.140086,...,0,0,0,0,0,1,0,0,0,1
4,1008,0.405458,0.402221,0.453263,0.507894,0.568113,0.576616,0.541275,0.481495,0.264009,...,0,0,0,0,0,1,0,0,0,1

In [9]:
# combined.to_csv('/Users/dillorr/defaultRate/dillon/defaultRate/data/modeling/combined.csv', index=False)